version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gorm
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
    ports:
      - 5432:5432